services:
  - type: web
    name: virtual-power-plant
    runtime: python
    plan: free
    rootDir: "flask app"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 180
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
